'use client';
import {useEffect,useState} from 'react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
function Choices({label,values,value,onChange}:{label:string;values:string[];value:string;onChange:(v:string)=>void}){return <RadioGroup aria-label={label} value={value} onValueChange={onChange} className="choice-group">{values.map((v,i)=><label className="choice" key={v}><RadioGroupItem value={v} aria-label={v}/>{v}</label>)}</RadioGroup>}
export function Booking(){const [date,setDate]=useState('');const [slot,setSlot]=useState('18:00');const [mode,setMode]=useState('Корт');const [done,setDone]=useState(false);const [error,setError]=useState('');const today=new Date().toLocaleDateString('en-CA');
useEffect(()=>{setDate(new Date().toLocaleDateString('en-CA'))},[]);
return <div className="booking"><span className="eyebrow">Ваша следующая игра</span><h3>Выберите время на корте</h3><p className="form-note">Тестовое расписание. Реальная доступность и стоимость не подключены.</p><Tabs value={mode} onValueChange={v=>{setMode(v);setDone(false)}}><TabsList aria-label="Формат игры" className="mt-5 mb-3"><TabsTrigger value="Корт">Корт</TabsTrigger><TabsTrigger value="Первое знакомство">Первое знакомство</TabsTrigger></TabsList><TabsContent value="Корт"><p className="small">Выберите удобное время для игры своей компанией.</p></TabsContent><TabsContent value="Первое знакомство"><p className="small">Демо сценария первого визита. Формат занятия нужно согласовать с клубом.</p></TabsContent></Tabs><form onSubmit={e=>{e.preventDefault();if(!date||date<today){setError('Выберите сегодняшнюю или будущую дату.');return}setError('');setDone(true)}}><label className="field mt-5">Дата игры<input type="date" required min={today} value={date} onChange={e=>{setDate(e.target.value);setDone(false)}}/></label><div className="date-row mt-3"><button type="button" className="textlink" onClick={()=>{setDate(today);setDone(false)}}>Сегодня</button><button type="button" className="textlink" onClick={()=>{const d=new Date();d.setDate(d.getDate()+1);setDate(d.toLocaleDateString('en-CA'));setDone(false)}}>Завтра</button></div><fieldset><legend>Начало игры · пример слотов</legend><Choices label="Время игры" values={['09:00','11:00','16:00','18:00','20:00']} value={slot} onChange={v=>{setSlot(v);setDone(false)}}/></fieldset><div className="small">Выбрано: <strong>{slot} · {mode}</strong></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button" type="submit">Проверить выбор <span>↗</span></button><p className="form-note">Это демонстрация: без оплаты и передачи персональных данных.</p>{done&&<div className="result" role="status"><strong>Ваш выбор: {date.split('-').reverse().join('.')} в {slot}</strong><p>Сценарий пройден. Корт не забронирован, данные клубу не отправлены.</p><button type="button" className="textlink mt-3" onClick={()=>setDone(false)}>Изменить выбор</button></div>}</form></div>}
export function Interest({kind}:{kind:'education'|'ralf'}){const edu=kind==='education';const vals=edu?['Выбрать направление','Узнать об условиях','Задать вопрос']:['С чего начать','Обсудить уход','Узнать о записи'];const [value,setValue]=useState(vals[0]);const [done,setDone]=useState(false);return <div className="booking"><h3>{edu?'Что хотите узнать?':'Начнём с вашего вопроса'}</h3><Choices label={edu?'Цель обращения':'Тема обращения'} values={vals} value={value} onChange={v=>{setValue(v);setDone(false)}}/><button className="button" onClick={()=>setDone(true)}>Продолжить <span>↗</span></button><p className="form-note">Демонстрация первого шага записи. Контактные данные не запрашиваются и не отправляются.</p>{done&&<div className="result" role="status"><strong>{value}</strong><p>{edu?'В рабочей версии здесь появится связь с приёмной комиссией и выбранный способ ответа.':'В рабочей версии следующий шаг — выбор способа связи с администратором.'} Сейчас это тест, обращение не отправлено.</p><button className="textlink mt-3" onClick={()=>setDone(false)}>Вернуться к выбору</button></div>}</div>}
